# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Oguzhan Karaahmetoglu
title: Data Scientist
email: oguzhan.karaahmetoglu@hotmail.com
website: https://oguzhanka.github.io/oguzhankaraahmetoglu/

# Social links
# twitter_username: facespics
github_username:  Oguzhanka
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: oguzhan-karaahmetoglu
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Oguzhan Karaahmetoglu and I am a Data Scientist. Currently, I pursue my graduate studies at Bilkent University under the supervision of Prof. S. Serdar Kozat.
  I am currently employed as a full-time Data Scientist, where I am a part of an R&D team developing a spatio-temporal prediction framework. My research interests include 
  spatio-temporal prediction, online learning, point processes modeling, adaptive filtering and big data.

  I am most skilled in: <mark>Python</mark> and <mark>PyTorch</mark>

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal